language: python

dist: xenial
os: linux

python:
  - "3.7"

install:
  - pip install flake8
  - pip install flake8-docstrings
  - pip install pylint
  - pip install -r requirements.txt

script:
  - pylint
  - flake8 .
